### ISSUE TITLE
Incorrect v0.0.2 removed tag breaks go module system 

### ISSUE THREAD

**Issue by Jorropo** [ptxmac/multierrgroup#2]
Trying to build a project which depends on your module:
```
$ go build .
go: go.ptx.dk/multierrgroup@v0.0.2: reading go.ptx.dk/multierrgroup/go.mod at revision v0.0.2: unknown revision v0.0.2
```
We can see the `v0.0.2` version exists in the module cache https://pkg.go.dev/go.ptx.dk/multierrgroup?tab=versions however it does not in github https://github.com/ptxmac/multierrgroup/tags.

The correct way to remove versions (if that what you are trying to do) the correct way is to leave `v0.0.2` tagged but release a new `v0.0.3` which has a `retract` line in the `go.mod` files.
Please see https://go.dev/blog/go116-module-changes `Module retraction` section.
If you accidentally deleted the tag (which git tries to makes hard to do ?), push it back pretty please.

**Comment by ptxmac** [comment]
> If you accidentally deleted the tag (which git tries to makes hard to do ?), push it back pretty please

Sorry, I moved this project from gitlab to GitHub a while back, and looks like I didn't push all the tags
This have been solved now!

**Comment by Jorropo** [comment]
:heart: thx you this works now
